modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="porkys_betterminecraft"
version="1.1"
displayName="Porky's BetterMinecraft"
credits="Created using MCreator"
displayURL="https://mcreator.net"
authors="OfficialPorky, MCreator"
description='''
Porky's BetterMinecraft 'improves' the game in different ways.
'''

[[dependencies.porkys_betterminecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




