modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="porkys_betterminecraft"
version="1.0.0"
displayName="Porky's BetterMinecraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="wesle, MCreator"

[[dependencies.porkys_betterminecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




